### ISSUE TITLE
Ustalenia odnośnie zarządzania projektem

### ISSUE THREAD

**Issue by ZielonyBuszmen** [kasa2001/hackaton#10]
Ustalenia które wynikły z dzisiejszej rozmowy

- Każde zadanie robimy na osobnym branchu
- Aby zmergować swojego brancha do mastera musimy zrobić pull requesta
- Pull request może być zmergowany dopiero wtedy, gdy przejdzie Code Review
- Saxo nie może tyle pić przed kodowaniem
- Code Review danego zadania robią pozostali członkowie projektu
- Arek musi załatwić sobie słuchawki, by jego anime nikomu nie przeszkadzało
- Przed wrzuceniem kodu do repo musimy sprawdzić, czy on działa i nie rozwali połowy sytemu ;)
- Master to branch z działającym projektem - nie możemy wrzucić tam niedziałających bubli
- Testy jednostkowe możemy pisać (lub nie pisać) wg. własnego uznania

Mam też kilka ustaleń odnośnie tworzenia Issues na GitHubie
- Zarządzanie całym projektem będzie na trello (rozdzielanie zadań, krótkie opisy, jakieś screeny)
- Gdyby okazało się, że jest jakieś poważniejsze zadanie, które wymaga przedyskutowania lub rozkminy, to wówczas zkładamy Issue na githubie

**Comment by kasa2001** [comment]
A jeszcze jedno ustalenie

Pan Bzyk też nie powinien tyle pić :)

**Comment by ZielonyBuszmen** [comment]
Wrzuciłem ustalenia do readme.md. Czeka na wasze approvy ;) #12 
Ten temat zamykam
