### ISSUE TITLE
ctrl + f9

### ISSUE THREAD

**Issue by ZielonyBuszmen** [kasa2001/hackaton#4]
magiczny skrót ctrl + f9, rebuilduje iml i idea katalogi

**Comment by bolexpl** [comment]
i co?

**Comment by ZielonyBuszmen** [comment]
Wywal pliki .idea oraz iml i spróbuj go użyć ;)
Nie wiem co sakso robił przez ostatnią godzinę, ale koniec końców stworzył tylko jeden plik z klasą Main i wrzucił niepotrzebnie katalog .idea. A wszystko to przez 7 commitów o wdzięcznym message 'a' :D

**Comment by kasa2001** [comment]
No spróbuj spróbuj bzyku :)

Od razu może wywalmy projekt, co? 

Projekt bez tych plików przez IDE na którym pracujemy jest traktowany jako... nie wiadomo co. Pliki muszą być jeżeli nie chcesz tworzyć projektu na istniejącym źródle. Te pliki są konfiguracją dla IDE na którym pracujemy. Na pewno są dobre. U Arka i u mnie się projekt normalnie kompiluje.

**Comment by ZielonyBuszmen** [comment]
Na plik *.iml można się jeszcze zgodzić, ale na .idea nie ma mowy. Wywaliłem je, projekt działa identycznie jak działał wcześniej. Nie wrzucajcie tego folderu więcej, bo tylko zaśmiecicie projekt ustawieniami własnego środowiska ;)

**Comment by ZielonyBuszmen** [comment]
Słyszeliście zapewne o takiej opcji w IntelliJ?
![obraz](https://user-images.githubusercontent.com/15154575/31320168-4e2df952-ac70-11e7-8cba-c48032ff6d79.png)

Dlatego jak po pullu przestanie wam działać projekt, to zamknijcie go, i odpalcie raz jeszcze przez tą opcję co jest na screenie. Wyświetli wam się mały "wizard" z kilkoma okienkami. Wszędzie klikamy next next next i finish :D

**Comment by ZielonyBuszmen** [comment]
Zamykam wątek, wszystko zostało już tutaj wyjaśnione ;)
