### ISSUE TITLE
Gradle - menadżer pakietów dla Javy

### ISSUE THREAD

**Issue by ZielonyBuszmen** [kasa2001/hackaton#6]
Ostatnio widziałem, ze programisci Javy często wspominają (i korzystają) z takiego narzędzia. Link do wiki:

https://pl.wikipedia.org/wiki/Apache_Maven

Może poszukamy i poczytamy, z czym to się jje, itp? Może przyda się nam to w naszym projekcie? Co o tym myślicie Panowie?

Kolejny link: http://mvnrepository.com/

________________

Oprócz Mavena są jeszcze niby takie narzędzia jak: Ivy, Grape, Gradle, Bundlr, SBT, Leiningen (z tego co znalazłem i wyczytałem na necie). Widziałem też, ze Gradle jest jakoś "wbudowany" do IntelliJ, więc jeśli nie Maven to może Gradle? Ale tak jak mówię - trzeba o tym wszystkim poczytać, czy się opłaca i co wybrać

**Comment by bolexpl** [comment]
Gradla używałem w androidzie do budowania projektu (chyba coś jak makefile). Ale do końca nie wiem po co to w zwykłej javie.

**Comment by ZielonyBuszmen** [comment]
Arek - cytuję :

W czym może pomóc Gradle

Jak wspomniałem wcześniej Gradle służy do budowania projektów. Pod pojęciem „budowania projektów” tak naprawdę kryje się cała masa drobnych czynności. Zaczynając od najbardziej podstawowych, takich jak kompilowanie kodu źródłowego czy tworzenie pliku ze skompilowanymi klasami, na przykład pliku JAR (ang. Java Archive)2.

Jednak to nie koniec, dobrze byłoby uruchomić wszystkie testy, które sprawdzają poprawność działania kodu przed utworzeniem pliku JAR. W tym także pomoże Ci Gradle. Gradle pomoże też przy zarządzaniu zależnościami projektu.
Zarządzanie zależnościami

Większe projekty bazują na zewnętrznych bibliotekach. Przykładem takich zewnętrznych bibliotek jest na przykład Hibernate, Spring czy Guava.

Zewnętrzne biblioteki dostępne są jako skompilowane klasy spakowane w pliki JAR. Można je ściągnąć z tak zwanych repozytoriów. Jednym z najczęściej używanych repozytoriów jest centralne repozytorium Maven’a.

Tak samo jak Twój projekt może zależeć od innych bibliotek, podobnie może być z tymi bibliotekami, też mogą mieć swoje zależności. Innymi słowy Twój projekt może mieć tak zwane zależności pośrednie/przechodnie. Jeśli Twój projekt wymaga wielu dodatkowych bibliotek, zarządzanie wszystkimi zależnościami (pośrednimi i bezpośrednimi) nie jest takim łatwym zadaniem.

Gradle pobiera zależności, które wskażesz (w odpowiedni sposób), zajmując się także zależnościami pośrednimi.

Cytat z http://www.samouczekprogramisty.pl/wstep-do-gradle/

**Comment by bolexpl** [comment]
To teraz czym się różni gradle i maven?

**Comment by ZielonyBuszmen** [comment]
Tutaj jest to ładnie opisane (po polsku nawet) 
;-)
http://www.javaexpress.pl/article/show/Gradle__a_powerful_build_system?lang=pl

**Comment by kasa2001** [comment]
Maven'a głównie używałem do pobierania bibliotek

**Comment by ZielonyBuszmen** [comment]
I głównie do tego będziemy używać tych narzędzi. To co, Gradle?

**Comment by kasa2001** [comment]
Gradle'a ja nie znam. Z Mavena korzystałem więc z Mavenem sobie poradziłbym, ale trzeba się uczyć w końcu :)

**Comment by ZielonyBuszmen** [comment]
No to ja wybieram Gradle. 
A wy?

**Comment by kasa2001** [comment]
Bardziej mnie przekonuje Maven (pewnie przez springa)

**Comment by ZielonyBuszmen** [comment]
Czekamy na odpowiedź Arka, weź go kopnij, niech się odezwie ;-)

**Comment by kasa2001** [comment]
Spadaj :P

Zajęcia ma pewnie :)

A Ty na pocztę zaglądaj :-)

**Comment by bolexpl** [comment]
No to gradle :P

**Comment by ZielonyBuszmen** [comment]
Zamykam sprawę. Ostatecznie został wybrany **Gradle**
