### ISSUE TITLE
Konwencje pisania kodu w projekcie

### ISSUE THREAD

**Issue by ZielonyBuszmen** [kasa2001/hackaton#8]
Myślę, że w tym wątku ustalimy wspólne konwencje odnośnie pisania kodu. Zbierzemy je do kupy i wrzucimy do pliku readme.md. Moje propozycje:

- formatowanie kodu (ilość spacji w tabie, położenie nawiasów klamrowych, itp) niech będzie domyślne z IntelliJ IDEA
- style nazewnictwa -> klasy dużą literą (CamelCase), metody małą (lowerCamelCase), stałe DUŻYMI, zmienne lowerCamelCase
- nie używamy prefiksów typu _zmienna, x_zmienna, xZmienna, zmienna_x
- wszelkie nazwy klas, funkcji, zmiennych, stałych oraz paczek będą w języku angielskim

Tutaj znalazłem style od Googla, może byśmy je przejęli i zaczęli go używać u siebie?
https://google.github.io/styleguide/javaguide.html

**Comment by kasa2001** [comment]
ad. 1) ok
ad. 2) ok
ad. 3) ok
ad. 4) ok

Ja tak staram się robić, aczkolwiek czasem nie chce się wymyślać angielskich nazw :D

**Comment by ZielonyBuszmen** [comment]
@kasa2001 nic nie chcesz dodać? Wspominałeś jeszcze o takim czymś:

- do jednego pliku wrzucamy tylko jedną klasę. Nazwa pliku jest identyczna z nazwą klasy

Az tym wymyślaniem angielskich nazw - postaraj się czasami wymyślić, taka umiejętność przyda się w przyszłości.

**Comment by kasa2001** [comment]
To jest naturalna składnia Javy więc po co wspominać? :)

**Comment by ZielonyBuszmen** [comment]
Ok :) To nie wspominamy.

A tak jak mówię - proponuję, byśmy nazwy pisali w języku angielskim. Wiem że jest to trudne i trzeba czasami pogłówkować, jednakże przyda się to w przyszłości, bo jest to cenna umiejętność :)

**Comment by bolexpl** [comment]
No to ja proponuję po japońsku albo suahili :D

**Comment by ZielonyBuszmen** [comment]
Zamykam wątek. O ewentualnych poprawkach możemy pogadać w Pull Requeście #9
